server:
  port: 8083

spring:
  application:
    name: schedule-service
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/martial-arts
  datasource:
    url: jdbc:postgresql://postgres:5432/schedule_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health
