server:
  port: 8081

spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: kafka:9092

keycloak:
  url: ${KEYCLOAK_URL:http://keycloak:8080}
  realm: martial-arts
  client-secret: ${KEYCLOAK_SECRET:auth-service-secret}
  public-client: martial-arts-client

springdoc:
  swagger-ui:
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health
